# Generated by Django 4.1.7 on 2024-01-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
